var cameras =
	[{
  "id": 1,
  "first_name": "Brocky",
  "last_name": "Dulieu",
  "email": "bdulieu0@acquirethisname.com",
  "gender": "Bigender",
  "ip_address": "70.33.12.84",
  "image": "http://dummyimage.com/116x163.jpg/ff4444/ffffff"
}, {
  "id": 2,
  "first_name": "Amalie",
  "last_name": "Ivanishin",
  "email": "aivanishin1@bbb.org",
  "gender": "Non-binary",
  "ip_address": "184.134.146.166",
  "image": "http://dummyimage.com/176x210.png/ff4444/ffffff"
}, {
  "id": 3,
  "first_name": "Nanette",
  "last_name": "Williment",
  "email": "nwilliment2@nbcnews.com",
  "gender": "Genderfluid",
  "ip_address": "168.233.109.56",
  "image": "http://dummyimage.com/156x109.png/5fa2dd/ffffff"
}, {
  "id": 4,
  "first_name": "Levy",
  "last_name": "Appleyard",
  "email": "lappleyard3@etsy.com",
  "gender": "Bigender",
  "ip_address": "36.237.123.63",
  "image": "http://dummyimage.com/226x137.png/dddddd/000000"
}, {
  "id": 5,
  "first_name": "Blinnie",
  "last_name": "Grevel",
  "email": "bgrevel4@tripod.com",
  "gender": "Polygender",
  "ip_address": "235.102.175.161",
  "image": "http://dummyimage.com/208x112.jpg/ff4444/ffffff"
}, {
  "id": 6,
  "first_name": "Kynthia",
  "last_name": "Garrold",
  "email": "kgarrold5@diigo.com",
  "gender": "Bigender",
  "ip_address": "143.44.250.51",
  "image": "http://dummyimage.com/103x151.jpg/5fa2dd/ffffff"
}, {
  "id": 7,
  "first_name": "Anestassia",
  "last_name": "Fancourt",
  "email": "afancourt6@clickbank.net",
  "gender": "Polygender",
  "ip_address": "161.41.242.39",
  "image": "http://dummyimage.com/127x131.jpg/cc0000/ffffff"
}, {
  "id": 8,
  "first_name": "Prudy",
  "last_name": "MacRinn",
  "email": "pmacrinn7@nhs.uk",
  "gender": "Genderqueer",
  "ip_address": "164.111.127.94",
  "image": "http://dummyimage.com/172x155.jpg/ff4444/ffffff"
}, {
  "id": 9,
  "first_name": "Hunt",
  "last_name": "Egginton",
  "email": "hegginton8@mozilla.com",
  "gender": "Polygender",
  "ip_address": "107.48.76.212",
  "image": "http://dummyimage.com/153x175.png/cc0000/ffffff"
}, {
  "id": 10,
  "first_name": "Davita",
  "last_name": "Fulleylove",
  "email": "dfulleylove9@php.net",
  "gender": "Genderfluid",
  "ip_address": "185.92.122.248",
  "image": "http://dummyimage.com/211x162.png/ff4444/ffffff"
}]
export default cameras;